In [1]:
# working with math module
import math #import math module and all the functions within it

In [3]:
# use math.function to use the functions in math module
math.pi #pi number

3.141592653589793

In [4]:
 math.e #e number

2.718281828459045

In [5]:
#ceil: round number up to nearest integer 
math.ceil(4.6)

5

In [6]:
#floor: round number down to nearest integer
math.floor(5.8)

5

In [8]:
num_list = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
sum(num_list) #likely to give 0.899999999

0.8999999999999999

In [9]:
#use the fsum fuction in math module to deal with this, give more accurate result
math.fsum(num_list)

0.9

In [15]:
# Introducing Numpy
import numpy as np

In [12]:
#create a list 
some_list = [i for i in range(11)]

In [18]:
#turn some_list to array
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [19]:
some_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#make a range array
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
 #reshape array: turn array into multidimensional array
reshape_array = range_array.reshape(2, 4) #turn range_array into 2 rows and 4 columns array
reshape_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
#random is a sub module in numpy, and random is a function in random module
random_array = np.random.random((4, 5)) #create random 4 rows, 5 columns array
random_array

array([[0.10223558, 0.4111695 , 0.23579551, 0.09804845, 0.63097504],
       [0.46345121, 0.54593238, 0.53607333, 0.02572158, 0.22738329],
       [0.98825587, 0.67674279, 0.89490509, 0.79773437, 0.70639474],
       [0.37086139, 0.37876399, 0.66325001, 0.34617183, 0.70693734]])

In [25]:
# mean: calculate the average
np.mean(some_array)

5.0

In [26]:
np.median(some_array)

5.0

In [27]:
# square root: std
np.std(some_array)

3.1622776601683795

In [28]:
# Introducing Pandas
import pandas as pd

In [33]:
# DataFrame: an object that has rows and columns, use to hold data is table forms
# DataFrame is case sensitive
names_ages_genders = pd.DataFrame({
     "name": ["quan", "quy", "quyen", "duong"],
     "age": [25, 33, 35, 36],
     "gender": ["male", "female", "male", "female"]})

In [35]:
names_ages_genders #output is tabular table form

name  age  gender
0   quan   25    male
1    quy   33  female
2  quyen   35    male
3  duong   36  female

In [38]:
# describe function: give statistic overview of all the numeric columns in dataframe
names_ages_genders.describe()

age
count   4.00000
mean   32.25000
std     4.99166
min    25.00000
25%    31.00000
50%    34.00000
75%    35.25000
max    36.00000

In [39]:
#subset columns in DataFrame
subset_table = names_ages_genders[["name", "age"]]

In [40]:
subset_table

name  age
0   quan   25
1    quy   33
2  quyen   35
3  duong   36

In [41]:
# groupby function: group data to perform calculator
group_df = names_ages_genders.groupby(by = "gender").count()#count people in groups of gender

In [42]:
group_df

name  age
gender           
female     2    2
male       2    2