In [1]:
#store a file as variable
which_file = 'Creative Commons Attribution-ShareAlike 3.0 Unported.txt'
license_file = open(which_file, "r")

In [6]:
license_file.readine()

AttributeError: '_io.TextIOWrapper' object has no attribute 'readine'

In [8]:
license_file.read()

''

In [9]:
license_file.close()

In [11]:
#use context manager: with
with open(which_file, "r") as f:
    print(f.read()) #specify the f.read so it show all the content, not only f

Creative Commons

Attribution-ShareAlike 3.0 Unported

CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE LEGAL SERVICES. DISTRIBUTION OF THIS LICENSE DOES NOT CREATE AN ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS INFORMATION ON AN "AS-IS" BASIS. CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE INFORMATION PROVIDED, AND DISCLAIMS LIABILITY FOR DAMAGES RESULTING FROM ITS USE.
License
THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE COMMONS PUBLIC LICENSE ("CCPL" OR "LICENSE"). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.

BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.

1. 

In [12]:
# Test file: delimited files and CSV
# Delimiter files separate fields using a specific character: comma, tab, pipe,..

In [13]:
# Import flat Files and Numerric data using Numpy
import numpy as np #always import numpy first

In [14]:
sample_array = np.array([0, 0, 7])

In [15]:
type(sample_array)

numpy.ndarray

In [16]:
dir(sample_array) #dir function: show all function we can use on array

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [20]:
# numpy.loadtxt: use to load txt file
badges_saved_np = np.loadtxt("badges-five-numpy.txt") #the file need to be in the same directory

In [21]:
badges_saved_np #the file has become array

array([[1., 1., 3.],
       [2., 2., 3.],
       [3., 4., 3.],
       [4., 5., 3.],
       [5., 8., 3.]])

In [22]:
#size: check how many value
badges_saved_np.size

15

In [24]:
#shape: check how many rows and columns
badges_saved_np.shape

(5, 3)

In [26]:
#numeric txt file with comma
badges_comma = np.loadtxt("badges-five.txt")
#because data seperate by the comma look like float, python can not specify it

ValueError: could not convert string to float: '1,1,3'

In [27]:
#You have to specify that the separate is the comma
badges_comma = np.loadtxt("badges-five.txt", delimiter = ",")

In [28]:
badges_comma #now it works

array([[1., 1., 3.],
       [2., 2., 3.],
       [3., 4., 3.],
       [4., 5., 3.],
       [5., 8., 3.]])

In [30]:
#Load a subset of columns
badges_comma = np.loadtxt("badges-five.txt", delimiter = ",", usecols = (0,2))
#use only the first and third columns

In [31]:
badges_comma

array([[1., 3.],
       [2., 3.],
       [3., 3.],
       [4., 3.],
       [5., 3.]])

In [38]:
#If the numeric five has header, we can use skiprow to skip the first row
badges_header = np.loadtxt("badges-five-header.txt", delimiter =",", skiprows = 1)

In [39]:
badges_header

array([[1., 1., 3.],
       [2., 2., 3.],
       [3., 4., 3.],
       [4., 5., 3.],
       [5., 8., 3.]])

In [41]:
#dtype: check the type of data in files
badges_header.dtype

dtype('float64')

In [44]:
#add a particular value to columns
def increase(the_id):
    return int(the_id) + 1000 #add index start with 1000 for every columns
badges_id = np.loadtxt("badges-five.txt", delimiter = ",", dtype = int, converters = {0: increase}) 

In [45]:
badges_id

array([[1001,    1,    3],
       [1002,    2,    3],
       [1003,    4,    3],
       [1004,    5,    3],
       [1005,    8,    3]])

In [47]:
#genfromtxt() function: use to deal with missing values
badges_missing_values = np.genfromtxt("badges-five-missing-value.txt", delimiter = ",")

In [48]:
badges_missing_values #missing value or not numeric data value now become nan 

array([[nan, nan, nan],
       [ 1.,  1.,  3.],
       [ 2.,  2.,  3.],
       [ 3.,  4.,  3.],
       [ 4.,  5., nan],
       [ 5.,  8.,  3.]])

In [49]:
badges_missing_values = np.genfromtxt("badges-five-missing-value.txt", delimiter = ",", skip_header = 1)

In [50]:
badges_missing_values #skip header or first row

array([[ 1.,  1.,  3.],
       [ 2.,  2.,  3.],
       [ 3.,  4.,  3.],
       [ 4.,  5., nan],
       [ 5.,  8.,  3.]])